apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - port: 80 #the public port
      name: http
      appProtocol: TCP
      targetPort: 3000 #the container port
  type: LoadBalancer