name: deploy-app
on:
  push:
    branches:
      - main
jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          create_credentials_file: true
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'setup terraform'
        uses: 'hashicorp/setup-terraform@v3'
        with:
          terraform_version: "1.1.7"
      - name: 'Terraform'
        run: |
          cd cloud/terraform
          terraform init
          terraform apply -auto-approve
